require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MusicasController do

  # This should return the minimal set of attributes required to create a valid
  # Musica. As you add validations to Musica, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MusicasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all musicas as @musicas" do
      musica = Musica.create! valid_attributes
      get :index, {}, valid_session
      assigns(:musicas).should eq([musica])
    end
  end

  describe "GET show" do
    it "assigns the requested musica as @musica" do
      musica = Musica.create! valid_attributes
      get :show, {:id => musica.to_param}, valid_session
      assigns(:musica).should eq(musica)
    end
  end

  describe "GET new" do
    it "assigns a new musica as @musica" do
      get :new, {}, valid_session
      assigns(:musica).should be_a_new(Musica)
    end
  end

  describe "GET edit" do
    it "assigns the requested musica as @musica" do
      musica = Musica.create! valid_attributes
      get :edit, {:id => musica.to_param}, valid_session
      assigns(:musica).should eq(musica)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Musica" do
        expect {
          post :create, {:musica => valid_attributes}, valid_session
        }.to change(Musica, :count).by(1)
      end

      it "assigns a newly created musica as @musica" do
        post :create, {:musica => valid_attributes}, valid_session
        assigns(:musica).should be_a(Musica)
        assigns(:musica).should be_persisted
      end

      it "redirects to the created musica" do
        post :create, {:musica => valid_attributes}, valid_session
        response.should redirect_to(Musica.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved musica as @musica" do
        # Trigger the behavior that occurs when invalid params are submitted
        Musica.any_instance.stub(:save).and_return(false)
        post :create, {:musica => {}}, valid_session
        assigns(:musica).should be_a_new(Musica)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Musica.any_instance.stub(:save).and_return(false)
        post :create, {:musica => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested musica" do
        musica = Musica.create! valid_attributes
        # Assuming there are no other musicas in the database, this
        # specifies that the Musica created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Musica.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => musica.to_param, :musica => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested musica as @musica" do
        musica = Musica.create! valid_attributes
        put :update, {:id => musica.to_param, :musica => valid_attributes}, valid_session
        assigns(:musica).should eq(musica)
      end

      it "redirects to the musica" do
        musica = Musica.create! valid_attributes
        put :update, {:id => musica.to_param, :musica => valid_attributes}, valid_session
        response.should redirect_to(musica)
      end
    end

    describe "with invalid params" do
      it "assigns the musica as @musica" do
        musica = Musica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Musica.any_instance.stub(:save).and_return(false)
        put :update, {:id => musica.to_param, :musica => {}}, valid_session
        assigns(:musica).should eq(musica)
      end

      it "re-renders the 'edit' template" do
        musica = Musica.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Musica.any_instance.stub(:save).and_return(false)
        put :update, {:id => musica.to_param, :musica => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested musica" do
      musica = Musica.create! valid_attributes
      expect {
        delete :destroy, {:id => musica.to_param}, valid_session
      }.to change(Musica, :count).by(-1)
    end

    it "redirects to the musicas list" do
      musica = Musica.create! valid_attributes
      delete :destroy, {:id => musica.to_param}, valid_session
      response.should redirect_to(musicas_url)
    end
  end

end
