require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PatrocinadoresController do

  # This should return the minimal set of attributes required to create a valid
  # Patrocinador. As you add validations to Patrocinador, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatrocinadoresController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all patrocinadores as @patrocinadores" do
      patrocinador = Patrocinador.create! valid_attributes
      get :index, {}, valid_session
      assigns(:patrocinadores).should eq([patrocinador])
    end
  end

  describe "GET show" do
    it "assigns the requested patrocinador as @patrocinador" do
      patrocinador = Patrocinador.create! valid_attributes
      get :show, {:id => patrocinador.to_param}, valid_session
      assigns(:patrocinador).should eq(patrocinador)
    end
  end

  describe "GET new" do
    it "assigns a new patrocinador as @patrocinador" do
      get :new, {}, valid_session
      assigns(:patrocinador).should be_a_new(Patrocinador)
    end
  end

  describe "GET edit" do
    it "assigns the requested patrocinador as @patrocinador" do
      patrocinador = Patrocinador.create! valid_attributes
      get :edit, {:id => patrocinador.to_param}, valid_session
      assigns(:patrocinador).should eq(patrocinador)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Patrocinador" do
        expect {
          post :create, {:patrocinador => valid_attributes}, valid_session
        }.to change(Patrocinador, :count).by(1)
      end

      it "assigns a newly created patrocinador as @patrocinador" do
        post :create, {:patrocinador => valid_attributes}, valid_session
        assigns(:patrocinador).should be_a(Patrocinador)
        assigns(:patrocinador).should be_persisted
      end

      it "redirects to the created patrocinador" do
        post :create, {:patrocinador => valid_attributes}, valid_session
        response.should redirect_to(Patrocinador.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved patrocinador as @patrocinador" do
        # Trigger the behavior that occurs when invalid params are submitted
        Patrocinador.any_instance.stub(:save).and_return(false)
        post :create, {:patrocinador => {}}, valid_session
        assigns(:patrocinador).should be_a_new(Patrocinador)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Patrocinador.any_instance.stub(:save).and_return(false)
        post :create, {:patrocinador => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested patrocinador" do
        patrocinador = Patrocinador.create! valid_attributes
        # Assuming there are no other patrocinadores in the database, this
        # specifies that the Patrocinador created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Patrocinador.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => patrocinador.to_param, :patrocinador => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested patrocinador as @patrocinador" do
        patrocinador = Patrocinador.create! valid_attributes
        put :update, {:id => patrocinador.to_param, :patrocinador => valid_attributes}, valid_session
        assigns(:patrocinador).should eq(patrocinador)
      end

      it "redirects to the patrocinador" do
        patrocinador = Patrocinador.create! valid_attributes
        put :update, {:id => patrocinador.to_param, :patrocinador => valid_attributes}, valid_session
        response.should redirect_to(patrocinador)
      end
    end

    describe "with invalid params" do
      it "assigns the patrocinador as @patrocinador" do
        patrocinador = Patrocinador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Patrocinador.any_instance.stub(:save).and_return(false)
        put :update, {:id => patrocinador.to_param, :patrocinador => {}}, valid_session
        assigns(:patrocinador).should eq(patrocinador)
      end

      it "re-renders the 'edit' template" do
        patrocinador = Patrocinador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Patrocinador.any_instance.stub(:save).and_return(false)
        put :update, {:id => patrocinador.to_param, :patrocinador => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested patrocinador" do
      patrocinador = Patrocinador.create! valid_attributes
      expect {
        delete :destroy, {:id => patrocinador.to_param}, valid_session
      }.to change(Patrocinador, :count).by(-1)
    end

    it "redirects to the patrocinadores list" do
      patrocinador = Patrocinador.create! valid_attributes
      delete :destroy, {:id => patrocinador.to_param}, valid_session
      response.should redirect_to(patrocinadores_url)
    end
  end

end
